DROP SEQUENCE EXEMPLAR_SEQ;

DROP SEQUENCE EMPRESTIMO_SEQ;

DROP TABLE EMPRESTIMO;

DROP TABLE EXEMPLAR;

DROP TABLE ALUNO;

DROP TABLE LIVRO;

CREATE SEQUENCE EXEMPLAR_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE EMPRESTIMO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE ALUNO
( 
    MATRICULA    DECIMAL(10)  NOT NULL PRIMARY KEY,
    NOME         VARCHAR(50)  NOT NULL,
    CURSO        VARCHAR(40)  NOT NULL,
    TELEFONE     DECIMAL(11)  NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL, 
    SITUACAO     CHAR(1)      NOT NULL
);

CREATE TABLE LIVRO
(
    ISBN           DECIMAL(13)   NOT NULL PRIMARY KEY,
    TITULO         VARCHAR(255)  NOT NULL,
    AUTOR          VARCHAR(50)   NOT NULL,
    EDITORA        VARCHAR(30)   NOT NULL,
    ANO_EDICAO     INT           NOT NULL,
    EDICAO         INT           NOT NULL,
    VALOR_COMPRA   DECIMAL(18,2) NOT NULL
);

CREATE TABLE EXEMPLAR
(
    ID             INT           NOT NULL PRIMARY KEY,
    ISBN_LIVRO     DECIMAL(13)   NOT NULL,
    EXEMPLAR_LOCAL CHAR(1)       NOT NULL,
    CONSTRAINT EXEMPLAR_LIVRO_FK 
                FOREIGN KEY (ISBN_LIVRO) 
                REFERENCES LIVRO(ISBN)
);

CREATE TABLE EMPRESTIMO
(
    ID              INT           NOT NULL PRIMARY KEY,
    ID_EXEMPLAR     INT           NOT NULL,
    MATRICULA_ALUNO DECIMAL(10)   NOT NULL,
    DATA_LOCACAO    DATE          NOT NULL,
    DATA_DEVOLUCAO  DATE          NULL,
    STATUS          CHAR(1)       NOT NULL,
    VALOR_MULTA     DECIMAL(18,2) NULL,
    CONSTRAINT EMPRESTIMO_EXEMPLAR_FK 
                FOREIGN KEY (ID_EXEMPLAR) 
                REFERENCES EXEMPLAR(ID),
    CONSTRAINT EMPRESTIMO_ALUNO_FK 
               FOREIGN KEY (MATRICULA_ALUNO) 
                REFERENCES ALUNO(MATRICULA)
);


SELECT * FROM ALUNO;
SELECT * FROM LIVRO;
SELECT * FROM EXEMPLAR;
SELECT * FROM EMPRESTIMO;
COMMIT;